//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardLifeAltLaunch.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardLifeAltLaunch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t log in ähnelt.
        /// </summary>
        internal static string AUTH_COULD_NOT_LOGIN {
            get {
                return ResourceManager.GetString("AUTH_COULD_NOT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. Please check{0}your email address. ähnelt.
        /// </summary>
        internal static string AUTH_EMAIL_FAILED {
            get {
                return ResourceManager.GetString("AUTH_EMAIL_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Something went wrong talking to the server.{0}{1} ähnelt.
        /// </summary>
        internal static string AUTH_GENERAL_FAILURE {
            get {
                return ResourceManager.GetString("AUTH_GENERAL_FAILURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. Please check{0}your password. ähnelt.
        /// </summary>
        internal static string AUTH_PASSWORD_FAILED {
            get {
                return ResourceManager.GetString("AUTH_PASSWORD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login failed. Server returned\ndata I couldn&apos;t understand! ähnelt.
        /// </summary>
        internal static string AUTH_SERVER_RETURNED_BAD_DATA {
            get {
                return ResourceManager.GetString("AUTH_SERVER_RETURNED_BAD_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Couldn&apos;t contact the server. Are you online?{0}{1} ähnelt.
        /// </summary>
        internal static string AUTH_SERVER_TALK_FAILED {
            get {
                return ResourceManager.GetString("AUTH_SERVER_TALK_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email Address ähnelt.
        /// </summary>
        internal static string MAINWIN_EMAIL_ADDRESS {
            get {
                return ResourceManager.GetString("MAINWIN_EMAIL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        internal static string MAINWIN_LOGIN {
            get {
                return ResourceManager.GetString("MAINWIN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string MAINWIN_PASSWORD {
            get {
                return ResourceManager.GetString("MAINWIN_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        internal static string MAINWIN_PLAY {
            get {
                return ResourceManager.GetString("MAINWIN_PLAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playing ähnelt.
        /// </summary>
        internal static string MAINWIN_PLAYING {
            get {
                return ResourceManager.GetString("MAINWIN_PLAYING", resourceCulture);
            }
        }
    }
}
